# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
inhibit_all_warnings!

def commonPods
  pod 'ReactiveObjC'
  pod 'MJExtension', '3.2.2'
  pod 'Toast', '~> 4.0.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'XLForm', '4.3'
  pod 'CocoaLumberjack'
  pod 'Masonry'
  pod 'Bugly'
  pod 'MJRefresh', '3.7.2'
  pod 'SDWebImage', '5.12.1'
end

target 'WindSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for WindmillSample
  commonPods
  pod 'SigmobAd-iOS', '4.2.0'
  
end
